FROM alpine:latest

RUN apk --no-cache add postgresql-client bash

WORKDIR /app

# Copiar scripts SQL
COPY db/init.sql db/dnd_tables.sql ./db/

# Copiar script de inicialização
COPY scripts/init-db.sh ./scripts/
RUN chmod +x ./scripts/init-db.sh

# Executar migrations
CMD ["./scripts/init-db.sh"]
