FROM golang:1.23

WORKDIR /app

RUN go install github.com/cosmtrek/air@v1.49.0

COPY go.mod go.sum* ./
RUN go mod download

COPY . .

RUN find . -name "*.go" -type f -exec sed -i 's|github.com/seu-usuario/rpg-saas-go|rpg-saas-backend|g' {} \; && \
    find . -name "*.go" -type f -exec sed -i 's|github.com/GustavoSRodrigues/taverna-do-mestre|rpg-saas-backend|g' {} \;

EXPOSE 8080

CMD ["air", "-c", ".air.toml"]